export type GenerateImageOptions = {
  style?: string | null;
};

// Returns a direct image URL generated by Fal (Flux.1-schnell)
export async function generateImage(description: string, opts: GenerateImageOptions = {}) {
  const apiKey = process.env.FAL_API_KEY;
  if (!apiKey) throw new Error('FAL_API_KEY not set');

  const endpoint = 'https://fal.run/fal-ai/flux.1-schnell';

  const res = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Authorization': `Key ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      prompt: description,
      // Some Fal routes accept additional params; keep minimal
      // You can extend with width/height/seed if needed
      style: opts.style || undefined,
    }),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`Fal API error: ${res.status} ${text}`);
  }

  const data = await res.json().catch(() => ({}));
  // Try common response shapes
  const url: string | undefined =
    data?.image?.url ||
    data?.output?.[0]?.url ||
    data?.data?.image?.url ||
    data?.images?.[0]?.url;

  if (!url) throw new Error('Fal API: image URL not found in response');
  return url as string;
}
