export type GenerateImageOptions = {
  style?: string | null;
};

// Returns a direct image URL generated by Fal (Flux schnell route)
export async function generateImage(description: string, opts: GenerateImageOptions = {}) {
  const apiKey = process.env.FAL_API_KEY;
  if (!apiKey) throw new Error('FAL_API_KEY not set');

  // Try the current Fal slugs in order. First: flux/schnell, then flux/dev as a fallback.
  const endpoints = [
    'https://fal.run/fal-ai/flux/schnell',
    'https://fal.run/fal-ai/flux/dev',
  ];

  let lastErr = '';
  for (const endpoint of endpoints) {
    const res = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Key ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt: description,
        // You can extend with width/height/seed if needed
        style: opts.style || undefined,
      }),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      lastErr = `${res.status} ${text}`;
      // Only attempt next endpoint on 404 (app not found). Other errors are thrown immediately.
      if (res.status === 404) continue;
      throw new Error(`Fal API error: ${lastErr}`);
    }

    const data = await res.json().catch(() => ({}));
    // Try common response shapes
    const url: string | undefined =
      data?.image?.url ||
      data?.output?.[0]?.url ||
      data?.data?.image?.url ||
      data?.images?.[0]?.url;

    if (url) return url as string;
    // If no URL found, try next endpoint
    lastErr = 'ok but no image URL in response';
  }

  throw new Error(`Fal API: all endpoints failed (${lastErr || 'unknown error'})`);
}
