"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg-primary text-text-primary font-sans p-6 md:p-12">
       <div className="max-w-3xl mx-auto">
        <div className="mb-8">
            <Link href="/" className="inline-flex items-center gap-2 text-text-secondary hover:text-text-primary transition-colors">
                <ArrowLeft className="w-4 h-4" />
                <span>Back to Home</span>
            </Link>
        </div>
        
        <h1 className="text-3xl md:text-4xl font-bold mb-8">Terms of Service</h1>
        
        <div className="space-y-6 text-text-secondary leading-relaxed">
            <p><strong>Last Updated:</strong> December 2025</p>

            <section>
                <h2 className="text-xl font-semibold text-text-primary mb-3">1. Acceptance of Terms</h2>
                <p>By using InkVerse, you agree to these terms. If you do not agree, please do not use our services.</p>
            </section>

            <section>
                <h2 className="text-xl font-semibold text-text-primary mb-3">2. User Accounts</h2>
                <p>You are responsible for safeguarding your account access. You must be at least 13 years old to use InkVerse.</p>
            </section>

            <section>
                <h2 className="text-xl font-semibold text-text-primary mb-3">3. Ownership & Intellectual Property</h2>
                <p><strong>Your Content:</strong> You retain ownership of the stories and original content you create on InkVerse.</p>
                <p><strong>AI Generations:</strong> You own the output generated by our AI tools to the fullest extent permitted by law.</p>
            </section>

            <section>
                <h2 className="text-xl font-semibold text-text-primary mb-3">4. Acceptable Use</h2>
                <p>You agree not to use InkVerse to generate illegal, harmful, or abusive content. We reserve the right to suspend accounts violating this policy.</p>
            </section>

            <section>
                <h2 className="text-xl font-semibold text-text-primary mb-3">5. Disclaimer</h2>
                <p>InkVerse is provided "as is" without warranties of any kind. We are not liable for any data loss or service interruptions.</p>
            </section>
        </div>
       </div>
    </div>
  );
}
